name: Create M3U Playlists

on:
  schedule:
    - cron: "5 4 * * *" # Run once a day
  workflow_dispatch: # Allow manual triggering

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt

      - name: Run the scraper
        run: uv run python scrape.py --filter-config channel_allow_filter_english.csv --playlist-name english --m3u-url https://raw.githubusercontent.com/Icastresana/lista1/refs/heads/main/peticiones

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add playlists/*.m3u
          git commit -m "Update m3u" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
